sudo: false
language: node_js
node_js:
- '5'
- '4'
env:
  global:
  - secure: HAD8/BquRmsmcWYu4whHSyNo0mRfpVmuaqkR2m2ymXxJWvkIcs48/tqau54QBjfTP2WRD5s3QjpYtx2g3lIYAXUS7lpSr49kv7ZLy8+bzWH9+/l6faWZcxeC1pcxoHbdavnkmLqdbAkZaOOXM+qD0OYZAlHWcClmR8zjoaEMemY=
  - secure: MbDYeyrfmrt2PVxdT6j+Q3+mY2McQ/MW/1oiq4mEyHZuub9DKxKXahM5LYhQUekCxGt1EvYf5KUhjmyyuAmuohWk3TDlO1I8BrjLe2K6qhty4OAim3tMyV+FX1ZkxWO2l5OWIfzcEM/nUwR2ZSJgt7rNcBpopvPuLJBd9f39HOI=
script: gulp build
deploy:
- provider: s3
  region: us-west-2
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  detect_encoding: true
  local_dir: build
  skip_cleanup: true
  bucket: voidjs-com
  on:
    branch: master
    node_js: '4'
- provider: s3
  region: us-west-2
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  detect_encoding: true
  local_dir: build
  skip_cleanup: true
  bucket: stage-voidjs-com
  on:
    branch: develop
    node_js: '4'